#!/usr/bin/env python3
"""Generate reference variants of the balances figure from the base config.

The manuscript figure is one particular set of four cases. These variants ask
the same question of other combinations -- a different magnitude rung, a
different background composition, a different pair of atmospheres -- and are
for the author's own reference, not for the paper.

Each variant OVERRIDES ONLY THE `columns` BLOCK AND THE OUTPUT NAME. Everything
else -- epochs, R = 250 binning, band definitions, axis limits, colours -- is
inherited from config_trappist_spectra_balances.yaml by reading it and
rewriting those two keys. That is the point of generating them rather than
copying the file: a change to the base (a new epoch, a different axis top)
reaches every variant on the next run, and the variants cannot silently drift
into using different conventions than the figure they are compared against.

    python make_variants.py            # write configs and render all variants
    python make_variants.py --list     # just show what would be made

Outputs land beside the manuscript figure as fig_balances_<name>.pdf/.eps.
"""

from __future__ import annotations

import argparse
import copy
import os
import subprocess
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "config_trappist_spectra_balances.yaml")

#: Per-atmosphere descriptive labels, so a column entry need only name the
#: atmosphere and the case.
ATM_LABEL = {
    "ben1": "ben1: dry land, N$_2$",
    "ben2": "ben2: dry land, CO$_2$",
    "hab1": "hab1: aquaplanet, N$_2$",
    "hab2": "hab2: aquaplanet, CO$_2$",
}

#: Short descriptors for the two eruption templates. Tambora is the sulfur-rich
#: end member (60 Tg SO2 against ~1 Tg H2O), Hunga the water-rich one (146 Tg
#: H2O against ~1 Tg SO2) -- and note the ladders scale DIFFERENT quantities,
#: so a "100x" Hunga carries the same sulfur as a 1x Hunga.
TEMPLATE = {
    "tambora":      ("sulfur-rich", "1$\\times$"),
    "tambora_100x": ("sulfur-rich", "100$\\times$"),
    "hunga":        ("water-rich",  "1$\\times$"),
    "hunga_100x":   ("water-rich",  "100$\\times$"),
}

#: The variants. Each is (name, title-ish description, [(atm, case), ...]).
VARIANTS = [
    (
        "1x",
        "the manuscript figure's four balances at the 1x rung",
        [("ben1", "tambora"), ("ben1", "hunga"),
         ("hab1", "tambora"), ("hab2", "tambora")],
    ),
    (
        "ben2_1x",
        "as 1x, but the dry columns on ben2 (CO2) instead of ben1 (N2)",
        [("ben2", "tambora"), ("ben2", "hunga"),
         ("hab1", "tambora"), ("hab2", "tambora")],
    ),
    (
        "ben2_100x",
        "as the manuscript figure, but the dry columns on ben2 instead of ben1",
        [("ben2", "tambora_100x"), ("ben2", "hunga_100x"),
         ("hab1", "tambora_100x"), ("hab2", "tambora_100x")],
    ),
    (
        "hunga_wet",
        "Hunga 1x and 100x on both moist atmospheres: the water-rich eruption "
        "where water is already abundant",
        [("hab1", "hunga"), ("hab1", "hunga_100x"),
         ("hab2", "hunga"), ("hab2", "hunga_100x")],
    ),
]


def make_columns(pairs):
    cols = []
    for atm, case in pairs:
        kind, rung = TEMPLATE[case]
        wet = atm.startswith("hab")
        cols.append({
            "key": f"exovolc_{atm}_{case}",
            "atm": atm,
            "case": case,
            "balance": f"{'wet' if wet else 'dry'} $+$ {kind} ({rung})",
            "atm_label": ATM_LABEL[atm],
            # The per-column italic note in the base config is a claim about
            # that specific case's behaviour. These variants are exploratory,
            # so no note is asserted -- an inherited one would very likely be
            # wrong for a different rung or atmosphere.
            "note": "",
        })
    return cols


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true",
                    help="show the variants without writing or rendering")
    ap.add_argument("--only", default=None,
                    help="render just this variant by name")
    args = ap.parse_args()

    with open(BASE) as f:
        base = yaml.safe_load(f)

    rc = 0
    for name, desc, pairs in VARIANTS:
        if args.only and name != args.only:
            continue
        cases = ", ".join(f"{a}/{c}" for a, c in pairs)
        print(f"\n=== {name}: {desc}")
        print(f"    {cases}")
        if args.list:
            continue

        cfg = copy.deepcopy(base)
        cfg["columns"] = make_columns(pairs)
        cfg["outfile_stem"] = f"fig_balances_{name}"

        path = os.path.join(HERE, f"config_variant_{name}.yaml")
        with open(path, "w") as f:
            f.write(f"# GENERATED by make_variants.py -- do not edit.\n"
                    f"# {desc}\n"
                    f"# Everything but `columns` and `outfile_stem` is inherited\n"
                    f"# from config_trappist_spectra_balances.yaml; change it there.\n")
            yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True,
                           default_flow_style=False)

        r = subprocess.run(
            [sys.executable, os.path.join(HERE, "plot_trappist_spectra_balances.py"),
             "--config", os.path.basename(path)],
            cwd=HERE, capture_output=True, text=True,
        )
        for line in r.stdout.splitlines():
            # Surface the substitution warning: it means an epoch the config
            # asked for is missing from the .npz, so a curve is mislabelled.
            if "NOTE: epoch" in line or "peak |diff|" in line or "shared raw" in line:
                print("   ", line.strip())
        if r.returncode != 0:
            print(f"    FAILED:\n{r.stderr[-1500:]}")
            rc = 1
        else:
            print(f"    wrote fig_balances_{name}.pdf / .eps")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
